runtime: python39
instance_class: F2

handlers:
# Only include this handler if you have a static directory with assets
- url: /static
  static_dir: static

- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: 'production'
  DAILY_BUDGET: "5"

automatic_scaling:
  max_instances: 2
  min_instances: 0
  max_concurrent_requests: 10
  min_pending_latency: 1000ms
  max_pending_latency: 5000ms